# Generated by Django 4.1.1 on 2022-10-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test2model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testid', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('salary', models.IntegerField()),
                ('mobilenum', models.IntegerField()),
            ],
        ),
    ]
