# Generated by Django 4.1.1 on 2022-10-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test3model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('empname', models.CharField(max_length=120)),
                ('empsalary', models.IntegerField()),
                ('empmob', models.IntegerField()),
            ],
        ),
    ]
